[build]
builder = "nixpacks"
buildCommand = "cd BizimSite.API && dotnet publish -c Release -o out"

[build.nixpacksPlan.phases.setup]
nixPkgs = ["dotnet-sdk_8"]

[deploy]
startCommand = "cd BizimSite.API/out && ./BizimSite.API"
restartPolicyType = "on_failure"
